apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-deployment
spec:
  selector:
    matchLabels:
      app: websocket
  template:
    metadata:
      labels:
        app: websocket
    spec:
      containers:
      - name: websocket
        image: waterball/allegro-websocket:latest
        resources:
        ports:
        - containerPort: 31274
        env:
        - name: "QuizGrpcApi"
          value: "http://quizzer:31924"
        - name: "ASPNETCORE_URLS"
          value: "http://0.0.0.0:31274;"
        - name: "RabbitMQConnection"
          value: "rabbitmq://rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  type: NodePort
  selector:
    app: websocket
  ports:
  - name: http
    protocol: TCP
    port: 31274
    targetPort: 31274
  - name: https
    protocol: TCP
    port: 31275
    targetPort: 31275
